name: Alembic Migrations

on:
  pull_request:
    branches: [main]
    paths:
      - 'alembic/**'

jobs:
  migrate:
    runs-on: ubuntu-latest # This specifies the host runner that will host the Docker container.
    container:
      image: python:3.12-slim # Using the slim version of Python 3.12 Docker image.
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install alembic psycopg2-binary
          pip install python-dotenv
          pip install sqlmodel

      - name: Run Alembic Migrations
        env:
          POSTGRES_USER: run
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_SERVER: 34.88.9.10
          POSTGRES_PORT: 5432
          POSTGRES_DB: backend
        run: alembic upgrade head