name: Coverage

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov alembic psycopg2-binary respx pytest-mock alembic
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Alembic Migrations
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_SERVER: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: postgres
      run: alembic upgrade head

    - name: Run tests with coverage
      env:
        SUPABASE_URL: "https://vlirscubbymrdmkcpkqm.supabase.co"
        SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsaXJzY3ViYnltcmRta2Nwa3FtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3MDYwNjA2MiwiZXhwIjoxOTg2MTgyMDYyfQ.jHstrQG-I3eU98EitUOoRpmYonBFjC9Kh40_v4cDY-Y"
        API_KEY: "YOUR_API_KEY"
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_SERVER: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: postgres
        TEXT_API_URL: https://text-v0.mentalmeasure.com/
        TEXT_API_TOKEN: Very_secret_key_54321
        TEST_USER_SUPABASE_PASSWORD: "12345678"
        TESTER_API_URL: https://tester-v0.mentalmeasure.com/
        TESTER_API_TOKEN: Very_secret_key_54321
        DATA_API_URL: https://data-v0.mentalmeasure.com/
        DATA_API_TOKEN: "Very_secret_key_54321"
        ANALYZER_API_URL: https://analyzer-v0.mentalmeasure.com/
        ANALYZER_API_TOKEN: Very_secret_key_54321
        AUTH_API_URL: https://auth-v0.mentalmeasure.com/
      run: pytest --cov-report term --cov=app tests/ --cov-report xml

    - name: Python Coverage
      uses: orgoro/coverage@v3.1
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        thresholdAll: 0.85
        thresholdNew: 0.80
        thresholdModified: 0.9